version: '2'

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: app_net

volumes:
  artifactory_repo_data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/volumes/artifactory/artifactory
  artifactory_db_data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/volumes/artifactory/postgresql

services:
  postgresql:
    image: docker.bintray.io/postgres:9.5.2
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=artifactory
    volumes:
     - artifactory_db_data:/var/lib/postgresql/data
    networks:
     - backend
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.5.2
    container_name: artifactory
    ports:
     - 8088:8081
    depends_on:
     - postgresql
    links:
     - postgresql
    volumes:
     - artifactory_repo_data:/var/opt/jfrog/artifactory
    networks:
     - backend
     - frontend
    environment:
     - DB_TYPE=postgresql
     - DB_USER=artifactory
     - DB_PASSWORD=artifactory
     - VIRTUAL_HOST=artifactory.imulab.io
     - VIRTUAL_PORT=8088
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000