version: '2'

services:
 registry:
  image: registry:2
  volumes:
   - registry_data:/var/lib/registry
  ports:
   - 5000:5000
  environment:
   - VIRTUAL_HOST=registry.imulab.io
   - VIRTUAL_PORT=5000

networks:
  default:
    external:
      name: app_net

volumes:
  registry_data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/volumes/registry